#!/bin/sh

start() {
REBOOTNEEDED=0
echo "Checking for maxcpus and ad9364 mods..."
export `fw_printenv maxcpus`
export `fw_printenv attr_val`
## Check/set dual-core mode
if [ $maxcpus == 1 ]; then
	echo "Enabling dual-core mode..."
        fw_setenv maxcpus
        REBOOTNEEDED=1
fi
## Check/set 70-6000mhz trick (default is 325-3800Mhz)
if [ "$attr_val" != "ad9364" ]; then
	echo "Enabling 70-6000Mhz mod..."
        fw_setenv attr_name compatible
        fw_setenv attr_val "ad9364"
        REBOOTNEEDED=1
fi
if [ $REBOOTNEEDED == 1 ]; then
	echo "Rebooting!"
        pluto_reboot reset
else
	echo "Mods already in place, continuing."
	echo "Updating motd..."
	# Update motd
	cat /etc/motd.new >>/etc/motd
	/bin/sh /etc/init.d/S97autoreboot start &
fi
}

stop() {
echo
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
