#!/bin/sh

start() {
	. /bin/readsettings.sh >/dev/null
	echo "<BR>"
	echo "*** All programs have been stopped! ***"
	echo "<BR>"
	echo "LeanTRX is available here: <a href="/leantrx">http://$ip/leantrx</a>"
}


stop() {
        echo " "
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
