#!/bin/sh

start() {
	echo "<BR>"
	echo "*** All programs have been stopped! ***"
}


stop() {
        echo " "
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
