#!/bin/sh

[ -f /bin/openwebrx.sh ] || exit 0

start() {
	printf "Starting OpenWebRX: "
	screen -Dm /bin/openwebrx.sh $0 &
	. /bin/readsettings.sh >/dev/null
	echo "<BR> - Done - Available here:  <a href=\"http://$ip:$web_port\">http://$ip:$web_port</a>  "
}


stop() {
	printf "Stopping OpenWebRX: "
	killall python
	killall csdr
	killall nc
	killall nmux
	killall screen
	echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
