#!/bin/sh

[ -f /bin/SoapySDRServer ] || exit 0

start() {
	printf "Starting SoapyRemote: "
	screen -Dm /bin/soapyremote.sh $0 &
	. /bin/readsettings.sh >/dev/null
	echo "<BR> - Done - Available here:  $ip  "
	echo "<BR>You can also now use LeanTRX <a href="/leantrx/">here</a>.
}


stop() {
	printf "Stopping SoapyRemote: "
	killall SoapySDRServer
	killall screen
	echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
