#!/bin/sh

# Read settings from NVRAM
. /bin/readsettings.sh >/dev/null

start() {
	if [ "$updatesrunning" = "y" ]; then
		exit
	fi
	if [ "$autoupdate" = "y" ]; then
		updatesrunning=y
		sed -i 's/updatesrunning=n/updatesrunning=y/' /root/plutoweb.conf
		# Start downloading and updating
		wget -qT 15 -O /root/update.zip.md5sum --no-check-certificate https://raw.githubusercontent.com/unixpunk/PlutoWeb/master/plutoweb/update.zip.md5sum
		if [ ! -f /root/update.zip.md5sum ] || [ ! -s /root/update.zip.md5sum ]; then
			echo "*** Auto-updates enabled but unable to download md5sum ***" >>/etc/motd
			rm -f /root/update.zip*
			updatesrunning=n
			sed -i 's/updatesrunning=y/updatesrunning=n/' /root/plutoweb.conf
			exit
		fi
		if diff -q /root/update.zip.md5sum /root/.update.zip.md5sum; then
			echo "*** Auto-updates enabled - already up to date ***" >>/etc/motd
			rm -f /root/update.zip*
			updatesrunning=n
			sed -i 's/updatesrunning=y/updatesrunning=n/' /root/plutoweb.conf
			exit
		else
			wget -qT 15 -O /root/update.zip --no-check-certificate https://raw.githubusercontent.com/unixpunk/PlutoWeb/master/plutoweb/update.zip
			if [ ! -f /root/update.zip ] || [ ! -s /root/update.zip ]; then
                        echo "*** Auto-updates enabled but unable to download update.zip ***" >>/etc/motd
			rm -f /root/update.zip*
			updatesrunning=n
			sed -i 's/updatesrunning=y/updatesrunning=n/' /root/plutoweb.conf
			exit
			fi
			if [ "$(md5sum -b /root/update.zip | awk -F\\  '{ print $1 }')" = "$(cat /root/update.zip.md5sum | awk -F\\  '{ print $1 }')" ]; then
			cd / && unzip -uo /root/update.zip && echo "*** Auto-updates enabled and an update completed successfully ***" >>/etc/motd
			rm -f /root/update.zip* /root/plutoweb.conf
			updatesrunning=n
			exit
			else
			echo "*** Auto-updates enabled but md5 mismatch on update.zip ***" >>/etc/motd
			rm -f /root/update.zip*
			updatesrunning=n
			sed -i 's/updatesrunning=y/updatesrunning=n/' /root/plutoweb.conf
			exit
			fi
		fi
	else
		echo "Auto-updates disabled" >>/etc/motd
	fi
# Starting update.zip watchdog in case someone manually drops in an update.zip file
# into the USB mass storage or /root
/bin/updatewatch.sh &
exit
}


stop() {
	echo "Done. (Nothing to stop)"
	sed -i 's/updatesrunning=y/updatesrunning=n/' /root/plutoweb.conf
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
