#!/bin/sh

# Read settings from NVRAM
. /bin/readsettings.sh >/dev/null

start() {
	if [ "$autoreboot" = "y" ]; then
		autoreboot=12
	fi
	if [ "$autoreboot" != "0" ] && [ "$autoreboot" != "n" ]; then
                echo "*** Auto-reboot enabled every $autoreboot hours ***" >>/etc/motd
                sleep "$autoreboot"h
                pluto_reboot reset
	else
		echo "Auto-reboot disabled" >>/etc/motd
	fi
}


stop() {
	echo "Nothing to stop..."
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
