#!/bin/sh

# Read settings from NVRAM
. /bin/readsettings.sh >/dev/null

start() {
	if [ $autoupdate = 'y' ]; then
		echo "*** Auto-updates not yet functional ***" >>/etc/motd
	else
		echo "Auto-updates disabled" >>/etc/motd
	fi
}


stop() {
	echo "Nothing to stop..."
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
