#! /bin/sh

[ -f /bin/dump1090.sh ] || exit 0

start() {
	printf "Starting dump1090: "
	screen -Dm /bin/dump1090.sh $1 &
	echo "done"
}


stop() {
        printf "Stopping dump1090: "
	killall dump1090
	killall screen
        echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
