#! /bin/sh
export `fw_printenv maxcpus`

## Check/set dual-core mode
if [ $maxcpus == 1 ]; then
	fw_setenv maxcpus
	pluto_reboot reset
fi

[ -f /bin/dump1090.sh ] || exit 0

start() {
	printf "Starting dump1090: "
	/bin/dump1090.sh &
	echo "done"
}


stop() {
        printf "Stopping dump1090: "
	killall dump1090
        echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
