#! /bin/sh

export `fw_printenv maxcpus`

if [ $maxcpus == 1 ]; then
	fw_setenv maxcpus
	pluto_reboot reset
fi

[ -f /bin/openwebrx.sh ] || exit 0

start() {
	printf "Starting OpenwebRx: "
	screen -Dm /bin/openwebrx.sh $0 &
	echo "done"
}


stop() {
	echo "ignoring, stop it yourself"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
