#! /bin/sh

[ -f /bin/SoapySDRServer ] || exit 0

start() {
	printf "Starting SoapyRemote: "
	/bin/SoapySDRServer --bind &
	echo "done"
}


stop() {
	printf "Stopping SoapyRemote: "
	killall SoapySDRServer
	echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
