#! /bin/sh
REBOOTNEEDED=0
export `fw_printenv maxcpus`
export `fw_printenv attr_val`

## Check/set dual-core mode
if [ $maxcpus == 1 ]; then
	fw_setenv maxcpus
	REBOOTNEEDED=1
fi

## Check/set 70-6000mhz trick (default is 325-3800Mhz)
if [ "$attr_val" != "ad9364" ]; then
        fw_setenv attr_name compatible
	fw_setenv attr_val "ad9364"
	REBOOTNEEDED=1
fi

if [ $REBOOTNEEDED == 1 ]; then
	pluto_reboot reset
fi


[ -f /bin/SoapySDRServer ] || exit 0

start() {
	printf "Starting SoapyRemote: "
	/bin/SoapySDRServer --bind &
	echo "done"
}


stop() {
	printf "Stopping SoapyRemote: "
	killall SoapySDRServer
	echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
